### ISSUE TITLE
Adding docstrings

### ISSUE THREAD

**Issue by danibene** [miso-sound/misosoupy#3]
These days, I usually like to document my python functions with either NumPy or Google-style docstrings. Thoughts/preferences?

**Comment by hansen508** [comment]
I admittedly did not know docstrings were a thing and had to google them. They seem similar enough to me that I don't have an immediate preference, so I'll let you choose and then learn that one!

**Comment by danibene** [comment]
Awesome! Want to go with NumPy then? If you feel comfortable/have time you could create a new branch based on `dev` and add docstrings to the existing functions, and open a pull request, otherwise I am happy to do it later

**Comment by hansen508** [comment]
Sounds good! Let me try first, I want to learn
