### ISSUE TITLE
plural or singular?

### ISSUE THREAD

**Issue by hansen508** [miso-sound/misosoupy#5]
[This is me practicing how to submit issues]

Which do you think sounds better:
Misophonia Stimuli Organization Using Python
or
Misophonia Stimulus Organization Using Python

**Comment by danibene** [comment]
I asked ChatGPT:

Which do you think sounds better:
Misophonia Stimuli Organization Using Python
or
Misophonia Stimulus Organization Using Python

ChatGPT
"Misophonia Stimulus Organization Using Python" sounds more grammatically correct and clear.

Shall we change it?

**Comment by hansen508** [comment]
ChatGPT has spoken! I think I agree, "Stimuli" sounded a tad clunky in my head. I vote changing, if you're not opposed!
